"""Initial migration for nautobot_ssot_fortinet — introduces FortinetStaticRoute (v3.1).

Hand-written rather than autogenerated because the app didn't previously have
any DB-backed models (everything before v3.1 went through Nautobot's existing
tables via SSoT pull/push Jobs). Patterned on the autogenerated migrations
from ``nautobot-firewall-models`` and ``nautobot-ssot``.

Dependencies pin to a stable mid-3.x migration of each app we FK to (``dcim``
and ``extras``) — Django picks any version ``>=`` the named one, so this
migration is forward-compatible with Nautobot patch releases.

If a future hand-edit goes wrong, regenerate with:

    nautobot-server makemigrations nautobot_ssot_fortinet
"""

import uuid

import django.core.serializers.json
import django.db.models.deletion
import taggit.managers
from django.db import migrations, models

import nautobot_ssot_fortinet.models


class Migration(migrations.Migration):
    """Create the FortinetStaticRoute table + indexes."""

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("extras", "0033_add__optimized_indexing"),
        ("dcim", "0009_add_natural_indexing"),
    ]

    operations = [
        migrations.CreateModel(
            name="FortinetStaticRoute",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "_custom_field_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                    ),
                ),
                ("vdom", models.CharField(default="root", max_length=32)),
                ("seq_num", models.PositiveIntegerField()),
                (
                    "destination",
                    models.CharField(
                        max_length=43,
                        validators=[nautobot_ssot_fortinet.models._validate_cidr],
                    ),
                ),
                ("gateway", models.GenericIPAddressField(blank=True, null=True)),
                ("distance", models.PositiveSmallIntegerField(default=10)),
                ("priority", models.PositiveSmallIntegerField(default=0)),
                ("blackhole", models.BooleanField(default=False)),
                ("comment", models.CharField(blank=True, default="", max_length=255)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fortinet_static_routes",
                        to="dcim.device",
                    ),
                ),
                (
                    "interface",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fortinet_static_routes_egress",
                        to="dcim.interface",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        through="extras.TaggedItem",
                        to="extras.Tag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fortinet Static Route",
                "verbose_name_plural": "Fortinet Static Routes",
                "ordering": ["device", "vdom", "seq_num"],
                "unique_together": {("device", "vdom", "seq_num")},
            },
        ),
    ]
